name: Deploy to Netlify

on:
  push:
    branches:
      - main # main 브랜치에 푸시될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16 # Netlify CLI가 요구하는 Node.js 버전

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Deploy to Netlify
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }} # Netlify 인증 토큰
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}       # Netlify 사이트 ID
      run: |
        npm install -g netlify-cli
        netlify deploy --dir=public --prod
